version: "3.8"

services:
  app:
    build: .
    container_name: rinha-backend
    ports:
      - "9999:9999"
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "200MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
